In [1]:
import torch
import os
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import graph_utils as gu

## Rho Analysis

In [ ]:
BASE_DIRS = [
    Path("results/afhq_cat/ot"),
    Path("results/celeba/ot"),
]

DATASET_NAMES = [
    "AFHQ Cat",
    "CELEBA",
]

METHODS = [
    "denoising",
    "gaussian_deblurring_FFT",
    "inpainting",
    "paintbrush_inpainting",
    "random_inpainting",
    "superresolution",
]

METRIC_CONFIG = {
    "final_psnr.txt":  ("psnr_rec", "PSNR"),
    "final_ssim.txt":  ("ssim_rec", "SSIM"),
    "final_lpips.txt": ("lpips_rec", "LPIPS"),
}

gu.plot_rho_analysis(
    base_dirs=BASE_DIRS,
    dataset_names=DATASET_NAMES,
    methods=METHODS,
    metric_config=METRIC_CONFIG,
    save_name="all_datasets_metrics_vs_rho_admm.png"
)

## Ablations result table

In [ ]:
ROOT_DIR = Path("results/celeba/ot")
OUT_XLSX = "ablation_summary_celeba.xlsx"

METHODS = [
    "pnp_flow_admm",
    "pnp_flow_fbs",
]

METRIC_FILES = {
    "psnr": "final_psnr.txt",
    "ssim": "final_ssim.txt",
    "lpips": "final_lpips.txt",
}

df = gu.collect_results(METHODS, METRIC_FILES, ROOT_DIR)

if df.empty:
    print("No matching results found.")
else:
    gu.save_outputs(df, OUT_XLSX)
    print(f"Saved Excel: {OUT_XLSX}")
    display(df)

## Result table on images for comparison

In [2]:
# ROOT_DIR = Path("results/celeba/ot")
ROOT_DIR = Path("results/afhq_cat/ot")

df = gu.extract_basic_metrics(ROOT_DIR, "metrics.xlsx")
display(df)
print(ROOT_DIR)

,task,method,ssim_rec,ssim_noisy,lpips_rec,lpips_noisy,psnr_rec,psnr_noisy
0,hdr_reconstruction,ADMM adaptive,0.8568,0.4896,0.0849,0.1722,26.2883,16.6003
1,hdr_reconstruction,ADMM deterministic,0.7469,0.4896,0.1289,0.1722,24.1074,16.6003
2,hdr_reconstruction,ADMM stochastic,0.7107,0.4896,0.3197,0.1722,22.9653,16.6003
3,hdr_reconstruction,d_flow,0.7533,0.4896,0.1580,0.1722,25.5927,16.6003
4,hdr_reconstruction,flow_dps,0.6205,0.4896,0.2952,0.1722,16.2544,16.6003
5,hdr_reconstruction,pnp_flow_fbs,0.8545,0.4896,0.1106,0.1722,24.9408,16.6003
6,inpainting,ADMM adaptive,0.8976,0.7272,0.0598,0.2154,27.8551,21.5279
7,inpainting,ADMM deterministic,0.7425,0.7272,0.1263,0.2154,24.8701,21.5279
8,inpainting,ADMM stochastic,0.7260,0.7272,0.3288,0.2154,24.7653,21.5279
9,inpainting,d_flow,0.7745,0.7272,0.1376,0.2154,26.3475,21.5279
10,inpainting,flow_dps,0.8251,0.7272,0.1903,0.2154,24.1916,21.5279
11,inpainting,flow_priors,0.8439,0.7272,0.1095,0.2154,24.7924,21.5279
12,inpainting,ot_ode,0.8746,0.7272,0.0954,0.2154,24.4686,21.5279
13,inpainting,pnp_flow_fbs,0.9011,0.7272,0.1270,0.2154,27.0793,21.5279
14,nonlinear_deblurring,ADMM adaptive,0.5921,0.4473,0.2733,0.5398,22.9643,20.2811
15,nonlinear_deblurring,ADMM deterministic,0.3524,0.4473,0.5827,0.5398,20.0144,20.2811
16,nonlinear_deblurring,ADMM stochastic,0.6068,0.4473,0.3213,0.5398,22.2737,20.2811
17,nonlinear_deblurring,d_flow,0.5981,0.4473,0.2043,0.5398,23.4464,20.2811
18,nonlinear_deblurring,flow_dps,0.3392,0.4473,0.5477,0.5398,17.6276,20.2811
19,nonlinear_deblurring,pnp_flow_fbs,0.4892,0.4473,0.5250,0.5398,19.7965,20.2811
20,phase_retrieval,ADMM adaptive,0.6160,0.3094,0.2910,1.3629,23.4349,9.7025
21,phase_retrieval,ADMM deterministic,0.2917,0.3094,0.6229,1.3629,13.0543,9.7025
22,phase_retrieval,ADMM stochastic,0.6722,0.3094,0.2572,1.3629,23.8327,9.7025
23,phase_retrieval,flow_dps,0.3221,0.3094,0.6430,1.3629,11.2524,9.7025
24,phase_retrieval,pnp_flow_fbs,0.3645,0.3094,0.4945,1.3629,14.2204,9.7025
25,random_inpainting,ADMM adaptive,0.9075,0.2141,0.0342,1.0799,33.3865,13.2495
26,random_inpainting,ADMM deterministic,0.4177,0.2141,0.4219,1.0799,22.6195,13.2495
27,random_inpainting,ADMM stochastic,0.8187,0.2141,0.2504,1.0799,29.9954,13.2495
28,random_inpainting,d_flow,0.8548,0.2141,0.0936,1.0799,31.3770,13.2495
29,random_inpainting,flow_dps,0.7616,0.2141,0.2548,1.0799,27.4324,13.2495
30,random_inpainting,flow_priors,0.9056,0.2141,0.0484,1.0799,32.0644,13.2495
31,random_inpainting,ot_ode,0.8506,0.2141,0.0860,1.0799,30.0453,13.2495
32,random_inpainting,pnp_flow_fbs,0.9267,0.2141,0.0530,1.0799,34.1146,13.2495
33,superresolution,ADMM adaptive,0.7518,0.2122,0.1536,0.8670,28.0035,11.5914
34,superresolution,ADMM deterministic,0.4376,0.2122,0.4124,0.8670,21.3989,11.5914
35,superresolution,ADMM stochastic,0.6962,0.2122,0.3602,0.8670,25.2612,11.5914
36,superresolution,d_flow,0.6246,0.2122,0.1639,0.8670,25.1365,11.5914
37,superresolution,flow_dps,0.6193,0.2122,0.3764,0.8670,22.0228,11.5914
38,superresolution,flow_priors,0.5754,0.2122,0.2727,0.8670,25.1262,11.5914
39,superresolution,ot_ode,0.7388,0.2122,0.1086,0.8670,26.7382,11.5914
40,superresolution,pnp_flow_fbs,0.7306,0.2122,0.2102,0.8670,26.0043,11.5914

results/afhq_cat/ot

In [2]:
ROOT_DIR = Path("results_rev3_2eval/celeba/ot")

df = gu.extract_basic_metrics(ROOT_DIR, "metrics.xlsx")
display(df)
print(ROOT_DIR)

,task,method,ssim_rec,ssim_noisy,lpips_rec,lpips_noisy,psnr_rec,psnr_noisy
0,denoising,pnp_flow_fbs,0.8692,0.2385,0.0813,0.5787,29.5216,16.4856
1,gaussian_deblurring_FFT,pnp_flow_fbs,0.8318,0.7423,0.1406,0.1383,27.6511,27.8094
2,inpainting,pnp_flow_fbs,0.8605,0.7397,0.0993,0.2049,27.0490,22.0390
3,paintbrush_inpainting,pnp_flow_fbs,0.7971,0.6779,0.1558,0.2781,24.6070,19.0980
4,random_inpainting,pnp_flow_fbs,0.7030,0.1832,0.2111,1.0442,23.4503,11.9891
5,superresolution,pnp_flow_fbs,0.6974,0.1926,0.2213,0.8480,22.1111,10.5857

results_rev3_2eval/celeba/ot

In [3]:
# ROOT_DIR = Path("results_celeba_rev_1/celeba/ot")

# df = gu.extract_basic_metrics_variable_params(ROOT_DIR, "metrics.xlsx")
# display(df)
# print(ROOT_DIR)
# /home/dibyanshuk/PNPFlow_admm/all_old_results/results_parameter_sweep/celeba
ROOT_DIR = Path("all_old_results/results_parameter_sweep/afhq_cat/ot")

df = gu.extract_basic_metrics_variable_params(ROOT_DIR, "metrics.xlsx")
display(df)
print(ROOT_DIR)

Found 144 experiment configurations.
Saved results to: metrics.xlsx

,task,method,steps_pnp,rho_admm,max_cgiter,cg_tol,save_norms_admm,adaptive_noise,deterministic_noise,t_schedule_gamma,psnr_rec,psnr_noisy,ssim_rec,ssim_noisy,lpips_rec,lpips_noisy,admm_gd_steps
0,inpainting,pnp_flow_admm,200,200,10,0.00001,False,True,False,0.2,22.1217,21.6270,0.7408,0.7286,0.1448,0.2158,10
1,inpainting,pnp_flow_admm,200,200,10,0.00001,False,True,False,1.0,25.0017,21.6270,0.7525,0.7286,0.1200,0.2158,10
2,inpainting,pnp_flow_admm,200,200,10,0.00001,False,True,False,1.8,25.4380,21.6270,0.7532,0.7286,0.1187,0.2158,10
3,inpainting,pnp_flow_admm,200,500,10,0.00001,False,True,False,0.2,22.3527,21.6270,0.7411,0.7286,0.1427,0.2158,10
4,inpainting,pnp_flow_admm,200,500,10,0.00001,False,True,False,1.0,25.0251,21.6270,0.7524,0.7286,0.1207,0.2158,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,superresolution,pnp_flow_admm,300,1000,10,0.00001,False,True,False,1.0,24.1627,11.4863,0.6098,0.2067,0.2039,0.8839,10
140,superresolution,pnp_flow_admm,300,1000,10,0.00001,False,True,False,1.8,22.6738,11.4863,0.5570,0.2067,0.2716,0.8839,10
141,superresolution,pnp_flow_admm,300,1500,10,0.00001,False,True,False,0.2,18.3317,11.4863,0.3991,0.2067,0.4103,0.8839,10
142,superresolution,pnp_flow_admm,300,1500,10,0.00001,False,True,False,1.0,22.1522,11.4863,0.5398,0.2067,0.2880,0.8839,10
143,superresolution,pnp_flow_admm,300,1500,10,0.00001,False,True,False,1.8,20.2036,11.4863,0.4738,0.2067,0.3900,0.8839,10

all_old_results/results_parameter_sweep/afhq_cat/ot

In [5]:
summary = gu.extract_rebuttal_metrics(
    # root_dir=Path("results/afhq_cat/ot"),
    root_dir=Path("results_celeba_rev_1/celeba/ot"),
    out_xlsx="metrics.xlsx",
)

print(summary)

Saved rebuttal metrics to: metrics.xlsx
                      task         method  n_runs  psnr_mean  psnr_std  \
0                denoising  pnp_flow_admm       5   22.29050  0.005340
1  gaussian_deblurring_FFT  pnp_flow_admm       5   27.56136  0.002669
2               inpainting  pnp_flow_admm       5   28.44506  0.016573
3    paintbrush_inpainting  pnp_flow_admm       5   24.97902  0.025553
4        random_inpainting  pnp_flow_admm       5   30.57456  0.035267
5          superresolution  pnp_flow_admm       5   29.18668  0.005920

   ssim_mean  ssim_std  lpips_mean  lpips_std
0    0.43804  0.000321     0.28770   0.001442
1    0.67402  0.000217     0.14996   0.000329
2    0.80160  0.000332     0.04704   0.000422
3    0.75862  0.000606     0.06808   0.000402
4    0.89690  0.000100     0.02432   0.000217
5    0.79604  0.000207     0.04594   0.000270

## Empirical Convergence

In [ ]:
ROOT_DIRS = [
    Path("results/afhq_cat_convergence_analysis/ot"),
    Path("results/celeba_convergence_analysis/ot"),
]

DATASET_NAMES = [
    "AFHQ Cat",
    "CELEBA",
]

gu.plot_convergence_two_datasets_shared_legend(
    root_dirs=ROOT_DIRS,
    dataset_names=DATASET_NAMES,
    batch=0,
    save_path=Path("results/convergence_analysis_all_datasets.png"),
    logy=True,
)

## Time and Memory

In [2]:
root_dir = Path("results/celeba/ot")

df_time_memory = gu.extract_time_memory_summary(root_dir)
gu.save_time_memory_summary(df_time_memory,xlsx_path="time_memory_summary_afhq_cat.xlsx")
display(df_time_memory)
print(root_dir)

,task,method,model,time_average,max_memory_average_gb,experiment_dir
0,hdr_reconstruction,ADMM adaptive,test,17.3893,0.305793,results/celeba/ot/hdr_reconstruction/pnp_flow_...
1,hdr_reconstruction,ADMM deterministic,test,16.1728,0.305426,results/celeba/ot/hdr_reconstruction/pnp_flow_...
2,hdr_reconstruction,ADMM stochastic,test,16.1335,0.305426,results/celeba/ot/hdr_reconstruction/pnp_flow_...
3,hdr_reconstruction,d_flow,test,65.6784,13.341276,results/celeba/ot/hdr_reconstruction/d_flow/te...
4,hdr_reconstruction,flow_dps,test,10.5546,0.303597,results/celeba/ot/hdr_reconstruction/flow_dps/...
5,hdr_reconstruction,pnp_flow_fbs,test,15.8248,0.300666,results/celeba/ot/hdr_reconstruction/pnp_flow_...
6,inpainting,ADMM adaptive,test,16.0152,0.305793,results/celeba/ot/inpainting/pnp_flow_admm/tes...
7,inpainting,ADMM deterministic,test,16.8529,0.305426,results/celeba/ot/inpainting/pnp_flow_admm/tes...
8,inpainting,ADMM stochastic,test,16.1023,0.305426,results/celeba/ot/inpainting/pnp_flow_admm/tes...
9,inpainting,d_flow,test,59.7521,13.327351,results/celeba/ot/inpainting/d_flow/test/steps...
10,inpainting,flow_dps,test,10.8118,0.303597,results/celeba/ot/inpainting/flow_dps/test/ste...
11,inpainting,flow_priors,test,35.3985,8.794149,results/celeba/ot/inpainting/flow_priors/test/...
12,inpainting,ot_ode,test,15.7945,2.319489,results/celeba/ot/inpainting/ot_ode/test/steps...
13,inpainting,pnp_flow_fbs,test,16.0875,0.300666,results/celeba/ot/inpainting/pnp_flow_fbs/test...
14,nonlinear_deblurring,ADMM adaptive,test,194.4890,0.787393,results/celeba/ot/nonlinear_deblurring/pnp_flo...
15,nonlinear_deblurring,ADMM deterministic,test,190.4957,0.787027,results/celeba/ot/nonlinear_deblurring/pnp_flo...
16,nonlinear_deblurring,ADMM stochastic,test,196.6801,0.787027,results/celeba/ot/nonlinear_deblurring/pnp_flo...
17,nonlinear_deblurring,d_flow,test,67.8145,13.955589,results/celeba/ot/nonlinear_deblurring/d_flow/...
18,nonlinear_deblurring,flow_dps,test,83.6724,0.784097,results/celeba/ot/nonlinear_deblurring/flow_dp...
19,nonlinear_deblurring,pnp_flow_fbs,test,94.4254,0.780068,results/celeba/ot/nonlinear_deblurring/pnp_flo...
20,phase_retrieval,ADMM adaptive,test,34.8430,0.308723,results/celeba/ot/phase_retrieval/pnp_flow_adm...
21,phase_retrieval,ADMM deterministic,test,35.8943,0.308723,results/celeba/ot/phase_retrieval/pnp_flow_adm...
22,phase_retrieval,ADMM stochastic,test,35.2113,0.308723,results/celeba/ot/phase_retrieval/pnp_flow_adm...
23,phase_retrieval,d_flow,test,131.7495,26.235283,results/celeba/ot/phase_retrieval/d_flow/test/...
24,phase_retrieval,flow_dps,test,11.5221,0.311165,results/celeba/ot/phase_retrieval/flow_dps/tes...
25,phase_retrieval,pnp_flow_fbs,test,31.1366,0.308967,results/celeba/ot/phase_retrieval/pnp_flow_fbs...
26,random_inpainting,ADMM adaptive,test,18.5354,0.305793,results/celeba/ot/random_inpainting/pnp_flow_a...
27,random_inpainting,ADMM deterministic,test,17.8621,0.305426,results/celeba/ot/random_inpainting/pnp_flow_a...
28,random_inpainting,ADMM stochastic,test,18.2651,0.305426,results/celeba/ot/random_inpainting/pnp_flow_a...
29,random_inpainting,d_flow,test,130.4909,13.347139,results/celeba/ot/random_inpainting/d_flow/tes...
30,random_inpainting,flow_dps,test,11.3576,0.303597,results/celeba/ot/random_inpainting/flow_dps/t...
31,random_inpainting,flow_priors,test,36.2238,8.794149,results/celeba/ot/random_inpainting/flow_prior...
32,random_inpainting,ot_ode,test,16.4997,2.319489,results/celeba/ot/random_inpainting/ot_ode/tes...
33,random_inpainting,pnp_flow_fbs,test,15.8704,0.300666,results/celeba/ot/random_inpainting/pnp_flow_f...
34,superresolution,ADMM adaptive,test,17.4060,0.367606,results/celeba/ot/superresolution/pnp_flow_adm...
35,superresolution,ADMM deterministic,test,16.7173,0.367240,results/celeba/ot/superresolution/pnp_flow_adm...
36,superresolution,ADMM stochastic,test,17.0019,0.367240,results/celeba/ot/superresolution/pnp_flow_adm...
37,superresolution,d_flow,test,64.9956,13.401577,results/celeba/ot/superresolution/d_flow/test/...
38,superresolution,flow_dps,test,10.9937,0.366097,results/celeba/ot/superresolution/flow_dps/tes...
39,superresolution,flow_priors,test,37.1411,8.855963,results/celeba/ot/superresolution/flow_priors/...
40,superresolution,ot_ode,test,15.8197,2.384338,results/celeba/ot/superresolution/ot_ode/test/...
41,superresolution,pnp_flow_fbs,test,15.3961,0.363166,results/celeba/ot/superresolution/pnp_flow_fbs...

results/celeba/ot