In [1]:
import torch
import os
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import graph_utils as gu

## Rho Analysis

In [ ]:
BASE_DIRS = [
    Path("results/afhq_cat/ot"),
    Path("results/celeba/ot"),
]

DATASET_NAMES = [
    "AFHQ Cat",
    "CELEBA",
]

METHODS = [
    "denoising",
    "gaussian_deblurring_FFT",
    "inpainting",
    "paintbrush_inpainting",
    "random_inpainting",
    "superresolution",
]

METRIC_CONFIG = {
    "final_psnr.txt":  ("psnr_rec", "PSNR"),
    "final_ssim.txt":  ("ssim_rec", "SSIM"),
    "final_lpips.txt": ("lpips_rec", "LPIPS"),
}

gu.plot_rho_analysis(
    base_dirs=BASE_DIRS,
    dataset_names=DATASET_NAMES,
    methods=METHODS,
    metric_config=METRIC_CONFIG,
    save_name="all_datasets_metrics_vs_rho_admm.png"
)

## Ablations result table

In [ ]:
ROOT_DIR = Path("results/celeba/ot")
OUT_XLSX = "ablation_summary_celeba.xlsx"

METHODS = [
    "pnp_flow_admm",
    "pnp_flow_fbs",
]

METRIC_FILES = {
    "psnr": "final_psnr.txt",
    "ssim": "final_ssim.txt",
    "lpips": "final_lpips.txt",
}

df = gu.collect_results(METHODS, METRIC_FILES, ROOT_DIR)

if df.empty:
    print("No matching results found.")
else:
    gu.save_outputs(df, OUT_XLSX)
    print(f"Saved Excel: {OUT_XLSX}")
    display(df)

## Result table on images for comparison

In [5]:
ROOT_DIR = Path("results/celeba/ot")

df = gu.extract_basic_metrics(ROOT_DIR, "metrics.xlsx")
display(df)
print(ROOT_DIR)

,task,method,ssim_rec,ssim_noisy,lpips_rec,lpips_noisy,psnr_rec,psnr_noisy
0,denoising,pnp_flow_admm,0.6072,0.2375,0.1904,0.5885,19.8525,16.4699
1,gaussian_deblurring_FFT,pnp_flow_admm,0.8207,0.7417,0.0725,0.1382,31.0954,27.8034
2,inpainting,pnp_flow_admm,0.7882,0.7391,0.0557,0.2049,27.6202,22.0367
3,paintbrush_inpainting,pnp_flow_admm,0.7563,0.6776,0.0731,0.2782,24.9177,19.0963
4,random_inpainting,pnp_flow_admm,0.8858,0.1832,0.0273,1.0445,30.5979,11.9890
5,superresolution,pnp_flow_admm,0.7933,0.1927,0.0580,0.8479,28.7181,10.5859

results/celeba/ot

In [2]:
ROOT_DIR = Path("results_rev3_2eval/celeba/ot")

df = gu.extract_basic_metrics(ROOT_DIR, "metrics.xlsx")
display(df)
print(ROOT_DIR)

,task,method,ssim_rec,ssim_noisy,lpips_rec,lpips_noisy,psnr_rec,psnr_noisy
0,denoising,pnp_flow_fbs,0.8692,0.2385,0.0813,0.5787,29.5216,16.4856
1,gaussian_deblurring_FFT,pnp_flow_fbs,0.8318,0.7423,0.1406,0.1383,27.6511,27.8094
2,inpainting,pnp_flow_fbs,0.8605,0.7397,0.0993,0.2049,27.0490,22.0390
3,paintbrush_inpainting,pnp_flow_fbs,0.7971,0.6779,0.1558,0.2781,24.6070,19.0980
4,random_inpainting,pnp_flow_fbs,0.7030,0.1832,0.2111,1.0442,23.4503,11.9891
5,superresolution,pnp_flow_fbs,0.6974,0.1926,0.2213,0.8480,22.1111,10.5857

results_rev3_2eval/celeba/ot

In [2]:
ROOT_DIR = Path("results_celeba_rev_1/celeba/ot")

df = gu.extract_basic_metrics_variable_params(ROOT_DIR, "metrics.xlsx")
display(df)
print(ROOT_DIR)

Found 750 experiment configurations.
Saved results to: metrics.xlsx

,task,method,steps_pnp,rho_admm,max_cgiter,cg_tol,save_norms_admm,adaptive_noise,deterministic_noise,t_schedule_gamma,psnr_rec,psnr_noisy,ssim_rec,ssim_noisy,lpips_rec,lpips_noisy
0,denoising,pnp_flow_admm,250,500,10,0.00001,True,True,False,1.0,22.298,16.4755,0.4385,0.2371,0.2855,0.5722
1,denoising,pnp_flow_admm,250,500,10,0.00001,True,True,False,1.0,22.298,16.4755,0.4385,0.2371,0.2874,0.5703
2,denoising,pnp_flow_admm,250,500,10,0.00001,True,True,False,1.0,22.298,16.4755,0.4385,0.2371,0.2878,0.5702
3,denoising,pnp_flow_admm,250,500,10,0.00001,True,True,False,1.0,22.298,16.4755,0.4385,0.2371,0.2884,0.5707
4,denoising,pnp_flow_admm,250,500,10,0.00001,True,True,False,1.0,22.298,16.4755,0.4385,0.2371,0.2894,0.5712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,superresolution,pnp_flow_admm,250,500,10,0.00001,True,True,False,1.0,29.185,10.4983,0.7959,0.1944,0.0455,0.8341
746,superresolution,pnp_flow_admm,250,500,10,0.00001,True,True,False,1.0,29.185,10.4983,0.7959,0.1944,0.0461,0.8343
747,superresolution,pnp_flow_admm,250,500,10,0.00001,True,True,False,1.0,29.185,10.4983,0.7959,0.1944,0.0460,0.8344
748,superresolution,pnp_flow_admm,250,500,10,0.00001,True,True,False,1.0,29.185,10.4983,0.7959,0.1944,0.0462,0.8344
749,superresolution,pnp_flow_admm,250,500,10,0.00001,True,True,False,1.0,29.185,10.4983,0.7959,0.1944,0.0459,0.8342

results_celeba_rev_1/celeba/ot

In [5]:
summary = gu.extract_rebuttal_metrics(
    # root_dir=Path("results/afhq_cat/ot"),
    root_dir=Path("results_celeba_rev_1/celeba/ot"),
    out_xlsx="metrics.xlsx",
)

print(summary)

Saved rebuttal metrics to: metrics.xlsx
                      task         method  n_runs  psnr_mean  psnr_std  \
0                denoising  pnp_flow_admm       5   22.29050  0.005340
1  gaussian_deblurring_FFT  pnp_flow_admm       5   27.56136  0.002669
2               inpainting  pnp_flow_admm       5   28.44506  0.016573
3    paintbrush_inpainting  pnp_flow_admm       5   24.97902  0.025553
4        random_inpainting  pnp_flow_admm       5   30.57456  0.035267
5          superresolution  pnp_flow_admm       5   29.18668  0.005920

   ssim_mean  ssim_std  lpips_mean  lpips_std
0    0.43804  0.000321     0.28770   0.001442
1    0.67402  0.000217     0.14996   0.000329
2    0.80160  0.000332     0.04704   0.000422
3    0.75862  0.000606     0.06808   0.000402
4    0.89690  0.000100     0.02432   0.000217
5    0.79604  0.000207     0.04594   0.000270

## Empirical Convergence

In [ ]:
ROOT_DIRS = [
    Path("results/afhq_cat_convergence_analysis/ot"),
    Path("results/celeba_convergence_analysis/ot"),
]

DATASET_NAMES = [
    "AFHQ Cat",
    "CELEBA",
]

gu.plot_convergence_two_datasets_shared_legend(
    root_dirs=ROOT_DIRS,
    dataset_names=DATASET_NAMES,
    batch=0,
    save_path=Path("results/convergence_analysis_all_datasets.png"),
    logy=True,
)

## Time and Memory

In [4]:
root_dir = Path("results_rev3_2eval/celeba/ot")

df_time_memory = gu.extract_time_memory_summary(root_dir)
gu.save_time_memory_summary(df_time_memory,xlsx_path="time_memory_summary_afhq_cat.xlsx")
display(df_time_memory)
print(root_dir)

,task,method,model,time_average,max_memory_average_gb,experiment_dir
0,denoising,pnp_flow_fbs,test,6.2448,0.300665,results_rev3_2eval/celeba/ot/denoising/pnp_flo...
1,gaussian_deblurring_FFT,pnp_flow_fbs,test,6.4047,0.302181,results_rev3_2eval/celeba/ot/gaussian_deblurri...
2,inpainting,pnp_flow_fbs,test,6.3540,0.300665,results_rev3_2eval/celeba/ot/inpainting/pnp_fl...
3,paintbrush_inpainting,pnp_flow_fbs,test,6.5603,0.300665,results_rev3_2eval/celeba/ot/paintbrush_inpain...
4,random_inpainting,pnp_flow_fbs,test,6.7030,0.300665,results_rev3_2eval/celeba/ot/random_inpainting...
5,superresolution,pnp_flow_fbs,test,6.5153,0.550665,results_rev3_2eval/celeba/ot/superresolution/p...

results_rev3_2eval/celeba/ot